name: delete-old-versions
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@7515f7a4f93408ebed9d5fbc7933145ac7105b78
        with: 
            owner: NamrataJha
            repo: 'action-demo'
            package-name: 'action-demo'
            min-versions-to-keep: 1


 


          
